"""adding quantity column to booking table

Revision ID: cfc627eadf6e
Revises: 9d7fef76ff2e
Create Date: 2026-08-05 09:55:35.517198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc627eadf6e'
down_revision: Union[str, Sequence[str], None] = '9d7fef76ff2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'quantity')
    # ### end Alembic commands ###
